Add test docker from the release download

diff --git a/config/jobs/ppc64le-cloud/build-docker/postsubmit-build-docker.yaml b/config/jobs/ppc64le-cloud/build-docker/postsubmit-build-docker.yaml
--- a/config/jobs/ppc64le-cloud/build-docker/postsubmit-build-docker.yaml
+++ b/config/jobs/ppc64le-cloud/build-docker/postsubmit-build-docker.yaml
@@ -169,7 +169,7 @@ postsubmits:
             cat env/date.list
 
             echo "* Start row-test-docker-staging.sh*"
-            ./prow-test-docker-staging.sh
+            ./prow-test-docker.sh staging
             rc=$?
             [ $rc != 0 ] && echo "ERROR: row-test-docker-staging exited with code:$rc"
             exit $rc
@@ -188,6 +188,65 @@ postsubmits:
         volumes:
         - name: docker-root
           emptyDir: {}
+
+    - name: postsubmit-test-docker-release
+      cluster: k8s-ppc64le-cluster
+      decorate: true
+      decoration_config:
+        timeout: 2h30m
+      run_if_changed: 'env/test-release.list'
+      branches:
+        - main
+      reporter_config:
+        slack:
+          channel: 'prow-job-notifications'
+          job_states_to_report:
+           - success
+           - failure
+           - error
+          report_template: 'Job {{.Spec.Job}} of type {{.Spec.Type}} ended with state {{.Status.State}}. <!subteam^S02N6DWBX0F> <{{.Status.URL}}|View logs>'
+      spec:
+        containers:
+        - image: quay.io/powercloud/docker-ce-build
+          command:
+          - /bin/bash
+          args:
+          - -c
+          - |
+            ##
+            # The job is populated with the file from the 'prow-job-tracking'.
+            # We need to switch to the main branch which contains the scripts need by this job.
+
+            #Timestamp file from the tracking branch (required to access the proper s3 directory)
+            TIMESTAMP_FILE=postsubmit-build-docker
+
+            FILE_URL="https://raw.githubusercontent.com/${REPO_OWNER}/${REPO_NAME}/prow-job-tracking/job/${TIMESTAMP_FILE}"
+
+            echo "* Retrieving the timestamp file from the tracking branch: ${FILE_URL}"
+            wget -O env/date.list ${FILE_URL}
+            cat env/date.list
+
+            echo "* Start row-test-docker-staging.sh*"
+            ./prow-test-docker.sh release
+            rc=$?
+            [ $rc != 0 ] && echo "ERROR: row-test-docker-staging exited with code:$rc"
+            exit $rc
+
+          securityContext:
+            privileged: true
+          volumeMounts:
+          - name: docker-root
+            mountPath: /var/lib/docker
+          env:
+            - name: S3_SECRET_AUTH
+              valueFrom:
+                secretKeyRef:
+                  name: docker-s3-credentials
+                  key: password
+        volumes:
+        - name: docker-root
+          emptyDir: {}
+
 
 ##########
 # DEV only
